services:
  - type: web
    name: ai-agent-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"

  - type: web
    name: ai-agent-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
